FROM docker.io/library/almalinux:minimal

ARG PDF_ENHANCER_VERSION

RUN adduser -m pdf

RUN microdnf --assumeyes update \
    && microdnf --assumeyes install \
        git \
        pip \
        python3.12 python3.12-pip\
    && rm -rf /var/cache/yum

USER pdf

WORKDIR /pdf_enhancer

RUN git clone https://github.com/tbelway/fork_pdf_enhancer.git /pdf_enhancer

RUN pip3.12 install -r requirements.txt

EXPOSE 7860

ENTRYPOINT /usr/bin/python3.12 /pdf_enhancer/pdf_enhancer.py
